spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@entrei-cluster.tygkjty.mongodb.net/entrei?retryWrites=true&w=majority
      auto-index-creation: true
      uuid-representation: standard

spring-doc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /swagger.yaml