openapi: 3.0.3
info:
  title: Entrei
  description: |-
    API para controle de convidados
  version: 1.0.0
servers:
  - url: http://localhost
tags:
  - name: QR Code
    description: Controle de QR codes
paths:
  /qr-codes:
    post:
      tags:
        - QR Code
      summary: Cria um novo QR code para o convidado.
      operationId: postQRCode
      requestBody:
        description: Dados para geração QR code.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QrCode'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QrCode'
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '405':
          description: Validation exception

components:
  schemas:
    QrCode:
      type: object
      properties:
        id:
          type: string
          format: uuid
        idEvento:
          type: string
          format: uuid
        nomeConvidado:
          type: string
        emailConvidado:
          type: string
        telefoneConvidado:
          type: string